# DO NOT USE TABS

# title of application
title: "CineFM"
# port where to start server
port: 8080

# root where to chroot left/right panel (no trailing /)
root-left: "/"
root-right: "/"
# if panel left/right cannot be modified
ro-left: false
ro-right: false
# sorting criteria for panel left/right (can be 'name', 'date', 'reverse-name', 'reverse-date')
sort-left: reverse-name
sort-right: reverse-date
# whether to show hidden files (.config, .xinit, etc)
show-hidden: false
# ftp folder relative to root-*
ftp-left:
  # folder relative to root, where ftp is mounted
  - folder: "ftp"
    host: "ftp://localhost:21/"
    user: "anonymous"
    passwd: "anonymous"
  #- folder: "ftp1"
  #  host: "ftp://localhost:2121/"
  #  user: "anonymous"
  #  passwd: "anonymous"
#ftp-right:
  # folder relative to root where ftp is mounted
  #- folder: "ftp"
  #  host: "ftp://localhost:21/"
  #  user: "admin"
  #  passwd: "admin"

# show the poweroff button
poweroff-button: false

# path where to place logfile
log-path: "/var/log/cinefm/cinefm.log"
